name: Build And Release
on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup nodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Building Resource Pack
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: TheRanks
          path: ./dist
  release-content:
    name: Releases
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download Artifacts
        id: download_artifacts
        uses: actions/download-artifact@v4
        with:
          name: TheRanks

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v2
          release_name: Release v2

      - name: Upload Version 6
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: TheRanks-1.16.2-1.16.5.zip
          asset_name: TheRanks-Java-1.16.2-1.16.5.zip
          asset_content_type: application/zip

      - name: Upload Version 7
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: TheRanks-1.17-1.17.1.zip
          asset_name: TheRanks-Java-1.17-1.17.1.zip
          asset_content_type: application/zip

      - name: Upload Version 8
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: TheRanks-1.18-1.18.2.zip
          asset_name: TheRanks-Java-1.18-1.18.2.zip
          asset_content_type: application/zip

      - name: Upload Version 9
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: TheRanks-1.19-1.19.2.zip
          asset_name: TheRanks-Java-1.19-1.19.2.zip
          asset_content_type: application/zip

      - name: Upload Version 12
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: TheRanks-1.19.3.zip
          asset_name: TheRanks-Java-1.19.3.zip
          asset_content_type: application/zip

      - name: Upload Version 13
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: TheRanks-1.19.4.zip
          asset_name: TheRanks-Java-1.19.4.zip
          asset_content_type: application/zip

      - name: Upload Version 15
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: TheRanks-1.20-1.20.1.zip
          asset_name: TheRanks-Java-1.20-1.20.1.zip
          asset_content_type: application/zip

      - name: Upload Version 18
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: TheRanks-1.20.2.zip
          asset_name: TheRanks-Java-1.20.2.zip
          asset_content_type: application/zip

      - name: Upload Version 23
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: TheRanks-1.20.3-1.20.4.zip
          asset_name: TheRanks-Java-1.20.3-1.20.4.zip
          asset_content_type: application/zip

      - name: Upload Version Bedrock
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: TheRanks-Bedrock.mcpack
          asset_name: TheRanks-Bedrock.mcpack
          asset_content_type: application/zip