name: Build And Release
on:
  push:
    branches:
      - "1.*"

jobs:
  build:
    name: Build Resource Pack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Building Resource Pack
        uses: actions/upload-artifact@v3
        with:
          name: TheRanks
          path: ./resourcepack
  release-content:
    name: Release Resource Pack
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download Artifacts
        id: download_artifacts
        uses: actions/download-artifact@v2
        with:
          name: TheRanks

      - name: Zip artifact for deployment
        run: zip TheRanks.zip ./* -r

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v.${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}

      - name: Upload Assets
        id: upload_assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: TheRanks.zip
          asset_name: TheRanks-${{ github.ref_name }}.zip
          asset_content_type: application/zip
